const postsData = [
  {
    id: 1,
    title: "Bihar Board 12th Result 2026",
    category: "Bihar Board",
    status: "Released",
    date: "2026-03-23",
    lastUpdated: "2026-03-25",
    organization: "Bihar School Examination Board",
    shortName: "BSEB",
    url: "posts/results/bihar-board-12th-result-2026.html",
    officialWebsite: "https://biharboardonline.bihar.gov.in",
    badge: "Result Live",
    priority: true,
    keywords: ["Bihar Board", "BSEB", "12th Result", "Inter Result", "Bihar Result"]
  },
  {
    id: 2,
    title: "Bihar Board 10th Result 2026",
    category: "Bihar Board",
    status: "Released",
    date: "2026-03-29",
    lastUpdated: "2026-03-29",
    organization: "Bihar School Examination Board",
    shortName: "BSEB",
    url: "posts/results/bihar-board-10th-result-2026.html",
    officialWebsite: "https://biharboardonline.bihar.gov.in",
    badge: "Result Live",
    priority: true,
    keywords: ["Bihar Board", "10th Result", "Matric Result", "BSEB"]
  },
  {
    id: 3,
    title: "BPSC School Teacher TRE 4.0 Online Form 2026 (46595 Posts Tentative)",
    category: "BPSC",
    status: "Latest Update",
    date: "2026-02-18",
    lastUpdated: "2026-05-16",
    organization: "Bihar Public Service Commission",
    shortName: "BPSC",
    url: "posts/jobs/bpsc-tre-4-vacancy-2026.html",
    officialWebsite: "https://bpsc.bihar.gov.in",
    badge: "Latest News",
    priority: true,
    keywords: ["BPSC TRE 4.0 2026", "BPSC School Teacher 46595 posts", "TRE 4.0 latest update", "BPSC teacher recruitment 2026", "BPSC exam calendar 2026", "bpsc.bihar.gov.in"]
  },
  {
    id: 4,
    title: "Bihar Police Constable Admit Card 2026",
    category: "Bihar Police",
    status: "Latest Update",
    date: "2026-05-13",
    lastUpdated: "2026-05-16",
    organization: "Central Selection Board of Constable",
    shortName: "CSBC",
    url: "posts/admit-card/bihar-police-constable-admit-card-2026.html",
    officialWebsite: "https://csbc.bihar.gov.in",
    badge: "Latest Update",
    priority: true,
    keywords: ["Bihar Police", "Constable", "Admit Card", "CSBC"]
  },
  {
    id: 5,
    title: "BSSC Office Attendant Main Admit Card 2026",
    category: "BSSC",
    status: "Released",
    date: "2026-05-12",
    lastUpdated: "2026-05-16",
    organization: "Bihar Staff Selection Commission",
    shortName: "BSSC",
    url: "posts/admit-card/bssc-office-attendant-main-admit-card-2026.html",
    officialWebsite: "https://bssc.bihar.gov.in",
    badge: "Latest Update",
    priority: true,
    keywords: ["BSSC", "Office Attendant", "Main Admit Card", "Bihar Admit Card"]
  },
  {
    id: 6,
    title: "Bihar Paramedical Admit Card 2026",
    category: "BCECEB",
    status: "Released",
    date: "2026-05-11",
    lastUpdated: "2026-05-16",
    organization: "Bihar Combined Entrance Competitive Examination Board",
    shortName: "BCECEB",
    url: "posts/admit-card/bihar-paramedical-admit-card-2026.html",
    officialWebsite: "https://bceceboard.bihar.gov.in",
    badge: "Latest Update",
    priority: true,
    keywords: ["Bihar Paramedical", "Admit Card", "BCECEB", "PM/PMM"]
  },
  {
    id: 7,
    title: "BPSSC SI Mains Admit Card 2026",
    category: "Bihar Police",
    status: "Released",
    date: "2026-05-10",
    lastUpdated: "2026-05-16",
    organization: "Bihar Police Subordinate Services Commission",
    shortName: "BPSSC",
    url: "posts/admit-card/bpssc-si-mains-admit-card-2026.html",
    officialWebsite: "https://bpssc.bihar.gov.in",
    badge: "Latest Update",
    priority: true,
    keywords: ["BPSSC", "SI Mains", "Admit Card", "Bihar Police"]
  },
  {
    id: 8,
    title: "Bihar Graduation Admission 2026",
    category: "Admission",
    status: "To Be Updated",
    date: "2026-05-09",
    lastUpdated: "2026-05-15",
    organization: "Bihar University / Related Authority",
    shortName: "UG Admission",
    url: "posts/admission/bihar-graduation-admission-2026.html",
    officialWebsite: "#",
    badge: "Recently Updated",
    priority: true,
    keywords: ["Bihar Graduation", "Admission", "UG", "Online Form"]
  },
  {
    id: 9,
    title: "Patna University Result 2026",
    category: "University",
    status: "To Be Updated",
    date: "2026-05-08",
    lastUpdated: "2026-05-15",
    organization: "Patna University",
    shortName: "PU",
    url: "posts/university/patna-university-result-2026.html",
    officialWebsite: "#",
    badge: "Recently Updated",
    priority: false,
    keywords: ["Patna University", "Result", "UG", "PG"]
  },
  {
    id: 10,
    title: "Bihar STET Result 2025 Out",
    category: "Result",
    status: "Released",
    date: "2026-02-18",
    lastUpdated: "2026-02-18",
    organization: "Official Update",
    shortName: "STET",
    url: "posts/results/bihar-stet-result-2026.html",
    officialWebsite: "https://biharresult.live/bihar-stet-result-2026/",
    badge: "Result Update",
    priority: false,
    keywords: ["Bihar Result 2026", "Bihar STET Result 2025 Out", "Latest Results 2026", "Sarkari Result Bihar", "Bihar Result Direct Link"]
  },
  {
    id: 11,
    title: "BPSC 72nd Pre Recruitment 2026",
    category: "BPSC",
    status: "Latest Update",
    date: "2026-05-07",
    lastUpdated: "2026-05-16",
    organization: "Bihar Public Service Commission (BPSC)",
    shortName: "BPSC",
    url: "posts/jobs/bpsc-72nd-pre-recruitment-2026.html",
    officialWebsite: "https://bpsc.bihar.gov.in/",
    badge: "Latest Update",
    priority: true,
    keywords: ["BPSC 72nd", "BPSC 72nd CCE 2026", "Bihar Government Jobs", "Apply Online Bihar Job", "Bihar Latest Jobs 2026"]
  },
  {
    id: 12,
    title: "BPSC 33rd Judicial Service Civil Judge Recruitment 2026",
    category: "BPSC",
    status: "Latest Update",
    date: "2026-02-24",
    lastUpdated: "2026-02-24",
    organization: "Bihar Public Service Commission (BPSC)",
    shortName: "BPSC",
    url: "posts/jobs/bpsc-33rd-judicial-service-civil-judge-recruitment-2026.html",
    officialWebsite: "https://bpsc.bihar.gov.in/",
    badge: "Application Update",
    priority: true,
    keywords: ["BPSC 33rd Judicial Service Civil Judge Recruitment 2026", "Bihar Latest Jobs 2026", "Bihar Government Jobs", "Bihar Sarkari Naukri", "BPSC 72nd CCE 2026"]
  },
  {
    id: 13,
    title: "BPSC Physics, Chemistry Professor Vacancy 2026",
    category: "BPSC",
    status: "Latest Update",
    date: "2026-03-28",
    lastUpdated: "2026-03-28",
    organization: "Bihar Public Service Commission (BPSC)",
    shortName: "BPSC",
    url: "posts/jobs/bpsc-physics-chemistry-professor-vacancy-2026.html",
    officialWebsite: "https://bpsc.bihar.gov.in/",
    badge: "Application Update",
    priority: true,
    keywords: ["BPSC Physics, Chemistry Professor Vacancy 2026", "Bihar Latest Jobs 2026", "Bihar Vacancy 2026", "Apply Online Bihar Job", "BPSC official link"]
  },
  {
    id: 14,
    title: "BPSSC Bihar ASI Technical Vacancy 2026 Online Form 22 Posts",
    category: "BPSC",
    status: "Latest Update",
    date: "2026-05-16",
    lastUpdated: "2026-05-16",
    organization: "Bihar Police Subordinate Services Commission",
    shortName: "BPSSC",
    url: "posts/jobs/bpssc-bihar-asi-technical-vacancy-2026-online-form-22-posts.html",
    officialWebsite: "https://bpssc.bihar.gov.in",
    badge: "Application Update",
    priority: true,
    keywords: ["BPSSC ASI Technical 2026", "Bihar ASI Technical 22 posts", "BPSSC Advt 07/2026", "Bihar Police Radio Wireless Recruitment", "bpssc.bihar.gov.in"]
  },
  {
    id: 15,
    title: "Bihar Board Class 10th, 12th Compartmental Result 2026",
    category: "Answer Key,Bihar Board",
    status: "Expected",
    date: "2026-05-16",
    lastUpdated: "2026-05-16",
    organization: "Bihar School Examination Board",
    shortName: "BSEB",
    url: "posts/answer-key/bihar-board-class-10th-12th-compartmental-result-2026.html",
    officialWebsite: "https://biharboardonline.com",
    badge: "Result Update",
    priority: true,
    keywords: ["Bihar Board Compartmental Result 2026", "BSEB 10th 12th compartmental special exam result", "Bihar board compartmental download", "biharboardonline.com", "BSEB special examination 2026"]
  },
  {
    id: 16,
    title: "DCECE Bihar Polytechnic Admit Card 2026 Download (OUT)",
    category: "Admit Card",
    status: "Released",
    date: "2026-05-16",
    lastUpdated: "2026-05-16",
    organization: "Bihar Combined Entrance Competitive Examination Board",
    shortName: "BCECEB",
    url: "posts/admit-card/dcece-bihar-polytechnic-admit-card-2026-download-out.html",
    officialWebsite: "https://bceceboard.bihar.gov.in",
    badge: "Admit Card Out",
    priority: true,
    keywords: ["DCECE Bihar Polytechnic Admit Card 2026 Download OUT", "BCECEB DCECE PE PM PMM Admit Card", "Bihar Polytechnic admission admit card 2026", "bceceboard.bihar.gov.in", "DCECE exam 23 24 May 2026"]
  }
];

window.postsData = postsData;
